version: "3.1"

networks:
  static-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
services:
  elasticsearch:
    image: elasticsearch:2.4.0
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    links:
      - spring-app:elasticsearch
    networks:
      static-network:
        ipv4_address: 172.31.0.10


  spring-app:
    image: sunrays86/springboot-springdata-elasticsearch-example-1.0:1.0
    restart: always
    networks:
      - static-network
  # Created custom network here